[[constraint]]
  name = "github.com/bitnami-labs/sealed-secrets"
  version = "0.9.8"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  version = "v2.2.3"

[[constraint]]
  branch = "master"
  name = "k8s.io/apimachinery"

[[constraint]]
  version = "0.9.11"
  name = "github.com/openfaas/openfaas-cloud"

[prune]
  go-tests = true
  unused-packages = true

# everything below need to be present for k8s.io/client-go to work with dep
# https://github.com/kubernetes/client-go/blob/master/INSTALL.md#dep-not-supported-yet

[[constraint]]
  name = "k8s.io/client-go"
  version = "0.15.0"

[[override]]
  name = "cloud.google.com/go"
  version = "v0.34.0"

[[override]]
  name = "github.com/Azure/go-autorest"
  version = "v11.1.2"

[[override]]
  name = "github.com/davecgh/go-spew"
  version = "v1.1.1"

[[override]]
  name = "github.com/dgrijalva/jwt-go"
  revision = "01aeca54ebda6e0fbfafd0a524d234159c05ec20"

[[override]]
  name = "github.com/docker/spdystream"
  revision = "449fdfce4d962303d702fec724ef0ad181c92528"

[[override]]
  name = "github.com/gogo/protobuf"
  revision = "342cbe0a04158f6dcb03ca0079991a51a4248c02"

[[override]]
  name = "github.com/golang/protobuf"
  version = "v1.2.0"

[[override]]
  name = "github.com/google/btree"
  revision = "7d79101e329e5a3adf994758c578dab82b90c017"

[[override]]
  name = "github.com/google/gofuzz"
  revision = "24818f796faf91cd76ec7bddd72458fbced7a6c1"

[[override]]
  name = "github.com/googleapis/gnostic"
  revision = "0c5108395e2debce0d731cf0287ddf7242066aba"

[[override]]
  name = "github.com/gophercloud/gophercloud"
  revision = "c818fa66e4c88b30db28038fe3f18f2f4a0db9a8"

[[override]]
  name = "github.com/gregjones/httpcache"
  revision = "787624de3eb7bd915c329cba748687a3b22666a6"

[[override]]
  name = "github.com/hashicorp/golang-lru"
  version = "v0.5.0"

[[override]]
  name = "github.com/imdario/mergo"
  version = "v0.3.5"

[[override]]
  name = "github.com/json-iterator/go"
  revision = "ab8a2e0c74be9d3be70b3184d9acc634935ded82"

[[override]]
  name = "github.com/modern-go/concurrent"
  revision = "bacd9c7ef1dd9b15be4a9909b8ac7a4e313eec94"

[[override]]
  name = "github.com/modern-go/reflect2"
  version = "v1.0.1"

[[override]]
  name = "github.com/peterbourgon/diskv"
  version = "v2.0.1"

[[override]]
  name = "github.com/pmezard/go-difflib"
  version = "v1.0.0"

[[override]]
  name = "github.com/spf13/pflag"
  version = "v1.0.1"

[[override]]
  name = "github.com/stretchr/testify"
  version = "1.2.2"

[[override]]
  name = "golang.org/x/crypto"
  revision = "e84da0312774c21d64ee2317962ef669b27ffb41"

[[override]]
  name = "golang.org/x/net"
  revision = "cdfb69ac37fc6fa907650654115ebebb3aae2087"

[[override]]
  name = "golang.org/x/oauth2"
  revision = "9f3314589c9a9136388751d9adae6b0ed400978a"

[[override]]
  name = "golang.org/x/sys"
  revision = "3b5209105503162ded1863c307ac66fec31120dd"

[[override]]
  name = "golang.org/x/text"
  revision = "e6919f6577db79269a6443b9dc46d18f2238fb5d"

[[override]]
  name = "golang.org/x/time"
  revision = "f51c12702a4d776e4c1fa9b0fabab841babae631"

[[override]]
  name = "gopkg.in/inf.v0"
  version = "v0.9.0"

#[[override]]
#  name = "gopkg.in/yaml.v2"
#  revision = "670d4cfef0544295bc27a114dbac37980d83185a"

[[override]]
  name = "k8s.io/api"
  version = "v0.15.10"

[[override]]
  name = "k8s.io/apimachinery"
  version = "v0.15.10"

[[override]]
  name = "k8s.io/kube-openapi"
  revision = "b3a7cee44a305be0a69e1b9ac03018307287e1b0"

[[constraint]]
  name = "github.com/alexellis/hmac"
  version = "1.2.0"
