environment:
  customers_url: "https://raw.githubusercontent.com/openfaas/openfaas-cloud/master/CUSTOMERS"
  gateway_url:  http://gateway.openfaas:8080/
  gateway_public_url: https://cloud.o6s.io/
  audit_url: http://gateway.openfaas:8080/function/audit-event
  repository_url: docker.io/ofcommunity/
  push_repository_url: docker.io/ofcommunity/
  basic_auth: true
  secret_mount_path: /var/openfaas/secrets
  builder_url: http://of-builder.openfaas:8080/
  s3_url: cloud-minio.openfaas.svc.cluster.local:9000
  s3_region: us-east-1
  s3_tls: false
  s3_bucket: pipeline
  readonly_root_filesystem: true
  scaling_min_limit: 1
  scaling_max_limit: 4

# To use a shared Docker Hub account.
#  repository_url: docker.io/ofcommunity/
#  push_repository_url: docker.io/ofcommunity/

# Private repo config
# repository_url: 127.0.0.1:5000
# push_repository_url: registry:5000
