[[constraint]]
  name = "github.com/openfaas/faas-cli"
  version = "0.9.3"

[[constraint]]
  name = "github.com/openfaas/openfaas-cloud"
  version = "0.13.2"

[[constraint]]
  name = "github.com/alexellis/hmac"
  version = "1.2"

[[constraint]]
  name = "github.com/alexellis/derek"
  version = "0.9.1"

[[override]]
  name = "gopkg.in/yaml.v2"
  version = "v2.2.3"

[[constraint]]
  branch = "master"
  name = "code.cloudfoundry.org/bytefmt"

[prune]
  go-tests = true
  unused-packages = true


