[[constraint]]
  name = "github.com/alexellis/derek"
  version = "0.5.0"

[[constraint]]
  name = "github.com/google/go-github"
  version = "15.0.0"

[[constraint]]
  name = "github.com/openfaas/openfaas-cloud"
  version = "0.9.2"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/alexellis/hmac"
  version = "1.2.0"
