apiVersion: apps/v1
kind: Deployment
metadata:
  name: of-builder
  labels:
    app.kubernetes.io/name: openfaas-cloud
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/component: of-builder
spec:
  replicas: {{ .Values.ofBuilder.replicaCount }}
  selector:
    matchLabels:
      app: of-builder
  template:
    metadata:
      annotations:
        prometheus.io.scrape: {{ .Values.global.prometheusScrape | quote }}
      labels:
        app: of-builder
    spec:
      volumes:
        - name: registry-secret
          secret:
            secretName: registry-secret
        - name: payload-secret
          secret:
            secretName: payload-secret
{{- if .Values.global.enableECR }}
        - name: aws-ecr-credentials
          secret:
            defaultMode: 420
            secretName: aws-ecr-credentials
{{- end }}
      containers:
        - name: of-builder
          image: {{ .Values.ofBuilder.image }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          readinessProbe:
            {{- if .Values.global.httpProbe }}
            httpGet:
              path: /healthz
              port: 8080
            {{- else }}
            exec:
              command:
                - wget
                - --quiet
                - --tries=1
                - --timeout=5
                - --spider
                - http://localhost:8080/healthz
            {{- end }}
            timeoutSeconds: 5
          env:
            - name: enable_lchown
              value: "true"
            - name: insecure
              value: "false"
            - name: buildkit_url
              value: "tcp://127.0.0.1:1234"
            - name: "disable_hmac"
              value: "false"
          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: registry-secret
              readOnly: true
              mountPath: "/home/app/.docker/"
            - name: payload-secret
              readOnly: true
              mountPath: "/var/openfaas/secrets/"
{{- if .Values.global.enableECR }}
            - name: aws-ecr-credentials
              mountPath: /home/app/.aws/
              readOnly: true
{{- end }}
        - name: of-buildkit
          args: ["--addr", "tcp://0.0.0.0:1234"]
          image: {{ .Values.buildKit.image }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - containerPort: 1234
              protocol: TCP
          securityContext:
            privileged: {{ .Values.buildKit.privileged }}
