[[constraint]]
  name = "github.com/minio/minio-go"
  version = "6.0.5"

[[constraint]]
  name = "github.com/openfaas/openfaas-cloud"
  version = "0.13.3"

[prune]
  go-tests = true
  unused-packages = true
