[[constraint]]
  name = "github.com/openfaas/openfaas-cloud"
  version = "0.13.3"

[[constraint]]
  branch = "master"
  name = "github.com/alexellis/hmac"

[prune]
  go-tests = true
  unused-packages = true
